version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "daily"
      time: "01:00"
    open-pull-requests-limit: 5
    target-branch: "main"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
      time: "01:00"
    open-pull-requests-limit: 5
    target-branch: "main"
