package tests;

import pages.LoginPage;
import org.openqa.selenium.WebDriver;
import org.testng.annotations.Test;

/**
 * Auto-generated by Ellithium AI Engine.
 */
public class LoginTest {

    private WebDriver driver; // Initialize via Ellithium's DriverFactory

    @Test
    public void testValidLogin() {
        new LoginPage(driver).login(email, pass);
    }
}
