package Ellithium.core.ai.generators;

import org.testng.Assert;
import org.testng.annotations.AfterMethod;
import org.testng.annotations.BeforeMethod;
import org.testng.annotations.Test;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;

public class FeatureFileModifierTest {

    private Path tempDir;

    @BeforeMethod
    public void setUp() throws IOException {
        tempDir = Files.createTempDirectory(Path.of("target"), "ffm-test-");
    }

    @AfterMethod
    public void tearDown() throws IOException {
        if (tempDir != null) {
            try (var stream = Files.walk(tempDir)) {
                stream.sorted(java.util.Comparator.reverseOrder())
                      .forEach(p -> { try { Files.deleteIfExists(p); } catch (IOException ignored) {} });
            }
        }
    }

    // ── createFeatureFile ────────────────────────────────────────────────────

    @Test
    public void createFeatureFile_newFile_writesFeatureTitle() throws IOException {
        Path file = tempDir.resolve("Login.feature");

        boolean result = FeatureFileModifier.createFeatureFile(
                file.toString(), "User Login",
                "  Scenario: Valid login\n    Given I open the app");

        Assert.assertTrue(result);
        Assert.assertTrue(Files.exists(file));
        String content = Files.readString(file);
        Assert.assertTrue(content.startsWith("Feature: User Login"),
                "Feature line must be first");
        Assert.assertTrue(content.contains("Valid login"));
    }

    @Test
    public void createFeatureFile_containsAutoGeneratedComment() throws IOException {
        Path file = tempDir.resolve("Search.feature");
        FeatureFileModifier.createFeatureFile(file.toString(), "Search", "  Scenario: basic search");
        Assert.assertTrue(Files.readString(file).contains("Auto-generated by Ellithium AI Engine"));
    }

    @Test
    public void createFeatureFile_createsParentDirectories() throws IOException {
        Path deep = tempDir.resolve("a/b/c/Deep.feature");
        boolean result = FeatureFileModifier.createFeatureFile(
                deep.toString(), "Deep Feature", "  Scenario: s");
        Assert.assertTrue(result);
        Assert.assertTrue(Files.exists(deep));
    }

    @Test
    public void createFeatureFile_scenarioContentPreserved() throws IOException {
        String scenario = "  Scenario: Login with valid credentials\n"
                + "    Given I am on the login page\n"
                + "    When I enter valid credentials\n"
                + "    Then I should be logged in";
        Path file = tempDir.resolve("Auth.feature");

        FeatureFileModifier.createFeatureFile(file.toString(), "Auth", scenario);

        String content = Files.readString(file);
        Assert.assertTrue(content.contains("I am on the login page"));
        Assert.assertTrue(content.contains("I should be logged in"));
    }

    // ── appendScenarios ───────────────────────────────────────────────────────

    @Test
    public void appendScenarios_existingFile_appendsToEnd() throws IOException {
        Path file = tempDir.resolve("Append.feature");
        FeatureFileModifier.createFeatureFile(file.toString(), "Append",
                "  Scenario: first scenario");

        boolean result = FeatureFileModifier.appendScenarios(file.toString(),
                "  Scenario: second scenario");

        Assert.assertTrue(result);
        String content = Files.readString(file);
        Assert.assertTrue(content.contains("first scenario"));
        Assert.assertTrue(content.contains("second scenario"));
        // second must come AFTER first
        Assert.assertTrue(content.indexOf("second scenario") > content.indexOf("first scenario"));
    }

    @Test
    public void appendScenarios_nonExistentFile_createsWithHeader() throws IOException {
        Path file = tempDir.resolve("sub/New.feature");

        boolean result = FeatureFileModifier.appendScenarios(file.toString(),
                "  Scenario: only scenario");

        Assert.assertTrue(result);
        Assert.assertTrue(Files.exists(file));
        String content = Files.readString(file);
        Assert.assertTrue(content.contains("Feature:"), "Auto-created file must have Feature: header");
        Assert.assertTrue(content.contains("only scenario"));
    }

    @Test
    public void appendScenarios_appendedSectionHasSeparatorComment() throws IOException {
        Path file = tempDir.resolve("Sep.feature");
        FeatureFileModifier.createFeatureFile(file.toString(), "Sep", "  Scenario: orig");
        FeatureFileModifier.appendScenarios(file.toString(), "  Scenario: appended");

        String content = Files.readString(file);
        Assert.assertTrue(content.contains("AI-generated scenario"),
                "Appended block should carry the AI-generated separator comment");
    }

    // ── scenarioExists ────────────────────────────────────────────────────────

    @Test
    public void scenarioExists_presentScenario_returnsTrue() throws IOException {
        Path file = tempDir.resolve("Exist.feature");
        FeatureFileModifier.createFeatureFile(file.toString(), "Exist",
                "  Scenario: User logs in with valid credentials");

        Assert.assertTrue(FeatureFileModifier.scenarioExists(
                file.toString(), "User logs in with valid credentials"));
    }

    @Test
    public void scenarioExists_absentScenario_returnsFalse() throws IOException {
        Path file = tempDir.resolve("Absent.feature");
        FeatureFileModifier.createFeatureFile(file.toString(), "Absent",
                "  Scenario: Known scenario");

        Assert.assertFalse(FeatureFileModifier.scenarioExists(
                file.toString(), "Unknown scenario"));
    }

    @Test
    public void scenarioExists_nonExistentFile_returnsFalse() {
        Assert.assertFalse(FeatureFileModifier.scenarioExists(
                tempDir.resolve("ghost.feature").toString(), "any scenario"));
    }

    @Test
    public void scenarioExists_nullTitle_returnsFalse() throws IOException {
        Path file = tempDir.resolve("Null.feature");
        FeatureFileModifier.createFeatureFile(file.toString(), "Null", "  Scenario: x");
        Assert.assertFalse(FeatureFileModifier.scenarioExists(file.toString(), null));
    }

    @Test
    public void scenarioExists_prefixOfLongerTitle_returnsTrue() throws IOException {
        // The implementation uses startsWith("Scenario: " + needle), so a search for
        // "User logs in" DOES match "User logs in with SSO" — document actual behaviour.
        Path file = tempDir.resolve("Partial.feature");
        FeatureFileModifier.createFeatureFile(file.toString(), "Partial",
                "  Scenario: User logs in with SSO");

        Assert.assertTrue(FeatureFileModifier.scenarioExists(
                file.toString(), "User logs in"),
                "startsWith match: 'User logs in' is a prefix of 'User logs in with SSO'");
    }

    @Test
    public void scenarioExists_scenarioOutline_returnsTrue() throws IOException {
        Path file = tempDir.resolve("Outline.feature");
        FeatureFileModifier.createFeatureFile(file.toString(), "Outline",
                "  Scenario Outline: Login with <role>");

        Assert.assertTrue(FeatureFileModifier.scenarioExists(
                file.toString(), "Login with <role>"));
    }

    @Test
    public void deriveFeatureTitle_fromHyphenatedFilename_isCapitalized() throws IOException {
        // When appendScenarios creates a new file, it derives the title from the filename
        Path file = tempDir.resolve("user-registration.feature");
        FeatureFileModifier.appendScenarios(file.toString(), "  Scenario: s");
        String content = Files.readString(file);
        // "user-registration" → "User Registration"
        Assert.assertTrue(content.contains("User Registration"),
                "Derived title should capitalize each word: " + content);
    }
}
