name: 'Setup Chrome'
description: 'Installs Chrome and ChromeDriver for UI testing'

runs:
  using: "composite"
  steps:
    - name: Install Chrome and ChromeDriver
      shell: bash
      run: |
        sudo apt update
        sudo apt install google-chrome-stable
        sudo apt-get update && sudo apt-get install -y google-chrome-stable
        CHROME_VERSION=$(google-chrome --version | awk '{print $3}' | cut -d. -f1)
        wget -q "https://chromedriver.storage.googleapis.com/$(curl -sS https://chromedriver.storage.googleapis.com/LATEST_RELEASE_$CHROME_VERSION)/chromedriver_linux64.zip"
        unzip chromedriver_linux64.zip
        sudo mv chromedriver /usr/local/bin/chromedriver
        google-chrome --version
        chromedriver --version