package Ellithium.core.ai.models;

import java.util.List;
import java.util.ArrayList;

/**
 * Data Transfer Object representing the assets generated by the AI
 * from a source test case.
 */
public class GeneratedAssets {

    private String targetPackage;
    private String testClass;
    private String testMethod;
    private String pomClass;
    private List<String> pomMethods;
    private String featureFile;

    public GeneratedAssets() {
        this.pomMethods = new ArrayList<>();
    }

    public GeneratedAssets(String targetPackage, String testClass, String testMethod, String pomClass, List<String> pomMethods, String featureFile) {
        this.targetPackage = targetPackage;
        this.testClass = testClass;
        this.testMethod = testMethod;
        this.pomClass = pomClass;
        this.pomMethods = pomMethods != null ? pomMethods : new ArrayList<>();
        this.featureFile = featureFile;
    }

    public String getTargetPackage() {
        return targetPackage;
    }

    public void setTargetPackage(String targetPackage) {
        this.targetPackage = targetPackage;
    }

    public String getTestClass() {
        return testClass;
    }

    public void setTestClass(String testClass) {
        this.testClass = testClass;
    }

    public String getTestMethod() {
        return testMethod;
    }

    public void setTestMethod(String testMethod) {
        this.testMethod = testMethod;
    }

    public String getPomClass() {
        return pomClass;
    }

    public void setPomClass(String pomClass) {
        this.pomClass = pomClass;
    }

    public List<String> getPomMethods() {
        return pomMethods;
    }

    public void setPomMethods(List<String> pomMethods) {
        this.pomMethods = pomMethods;
    }

    public String getFeatureFile() {
        return featureFile;
    }

    public void setFeatureFile(String featureFile) {
        this.featureFile = featureFile;
    }

    @Override
    public String toString() {
        return "GeneratedAssets{" +
                "targetPackage='" + targetPackage + '\'' +
                ", testClass='" + testClass + '\'' +
                ", testMethod='" + testMethod + '\'' +
                ", pomClass='" + pomClass + '\'' +
                ", pomMethods=" + pomMethods +
                ", featureFile='" + featureFile + '\'' +
                '}';
    }
}
