package Ellithium.core.ai.generators;

import Ellithium.core.logging.LogLevel;
import Ellithium.core.reporting.Reporter;

import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.nio.file.StandardOpenOption;

/**
 * Generates and modifies Cucumber {@code .feature} files.
 *
 * <p>Supports two operations:</p>
 * <ol>
 *   <li>Creating a brand-new feature file with a feature title and initial scenarios.</li>
 *   <li>Appending new scenarios to an existing feature file without overwriting it.</li>
 * </ol>
 */
public class FeatureFileModifier {

    /**
     * Creates a new Cucumber feature file.
     *
     * @param outputPath   Absolute path of the .feature file to create (e.g., "src/test/resources/features/Login.feature")
     * @param featureTitle The feature title (e.g., "User Login")
     * @param scenarios    The Gherkin scenario blocks to write as the initial content
     * @return true if the file was created successfully
     */
    public static boolean createFeatureFile(String outputPath, String featureTitle, String scenarios) {
        try {
            Path path = Paths.get(outputPath);
            Files.createDirectories(path.getParent());

            String content = "Feature: " + featureTitle + "\n"
                    + "  # Auto-generated by Ellithium AI Engine\n\n"
                    + scenarios.trim() + "\n";

            Files.writeString(path, content);
            Reporter.log("Feature file created: " + outputPath, LogLevel.INFO_GREEN);
            return true;
        } catch (IOException e) {
            Reporter.log("Failed to create feature file: " + e.getMessage(), LogLevel.ERROR);
            return false;
        }
    }

    /**
     * Appends new Gherkin scenarios to an existing .feature file.
     * If the file does not exist, it will be created.
     *
     * @param filePath      Absolute path to the existing .feature file
     * @param newScenarios  The Gherkin scenario block(s) to append
     * @return true if the scenarios were appended successfully
     */
    public static boolean appendScenarios(String filePath, String newScenarios) {
        try {
            Path path = Paths.get(filePath);

            if (!Files.exists(path)) {
                Reporter.log("Feature file not found, creating: " + filePath, LogLevel.INFO_YELLOW);
                Files.createDirectories(path.getParent());
                Files.writeString(path, newScenarios.trim() + "\n");
            } else {
                String separator = "\n\n  # AI-generated scenario\n";
                Files.writeString(path, separator + newScenarios.trim() + "\n",
                        StandardOpenOption.APPEND);
            }

            Reporter.log("Scenario appended to: " + filePath, LogLevel.INFO_GREEN);
            return true;
        } catch (IOException e) {
            Reporter.log("Failed to append scenario to feature file: " + e.getMessage(), LogLevel.ERROR);
            return false;
        }
    }

    /**
     * Checks if a scenario with a given title already exists in a feature file.
     * Used for idempotency — avoids generating duplicate scenarios.
     *
     * @param filePath      Absolute path to the .feature file
     * @param scenarioTitle The scenario title to search for (e.g., "User logs in with valid credentials")
     * @return true if the scenario already exists
     */
    public static boolean scenarioExists(String filePath, String scenarioTitle) {
        try {
            File file = new File(filePath);
            if (!file.exists()) return false;
            String content = Files.readString(Paths.get(filePath));
            return content.contains(scenarioTitle);
        } catch (IOException e) {
            return false;
        }
    }
}
