package Ellithium.core.ai.generators;

import Ellithium.core.logging.LogLevel;
import Ellithium.core.reporting.Reporter;
import com.github.javaparser.StaticJavaParser;
import com.github.javaparser.ast.CompilationUnit;
import com.github.javaparser.ast.body.BodyDeclaration;
import com.github.javaparser.ast.body.ClassOrInterfaceDeclaration;
import com.github.javaparser.ast.body.MethodDeclaration;

import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.List;
import java.util.Optional;

/**
 * Generates and modifies Java Page Object Model (POM) classes using AST.
 *
 * <p>Can either create a brand-new POM class file, or inject new locator fields
 * and business-action methods into an existing one, without breaking formatting.</p>
 *
 * <p>All generated code strictly follows Ellithium's Fluent POM pattern:
 * locators are {@code private final By}, and actions call
 * {@code driverActions.elements()...} returning {@code this} for chaining.</p>
 */
public class PomClassGenerator {

    /**
     * Creates a brand-new POM class file with the given locators and methods.
     *
     * @param outputPath    Absolute path of the .java file to create
     * @param packageName   Java package (e.g., "pages.login")
     * @param className     Class name (e.g., "LoginPage")
     * @param locatorFields List of raw field declarations (e.g., "private final By loginBtn = By.id(\"login\");")
     * @param methodBodies  List of raw method declarations
     * @return true if the file was created successfully
     */
    public static boolean createPomClass(String outputPath, String packageName, String className,
                                         List<String> locatorFields, List<String> methodBodies) {
        try {
            // Build the full class source
            StringBuilder sb = new StringBuilder();
            sb.append("package ").append(packageName).append(";\n\n");
            sb.append("import Ellithium.Utilities.interactions.DriverActions;\n");
            sb.append("import org.openqa.selenium.By;\n");
            sb.append("import org.openqa.selenium.WebDriver;\n\n");
            sb.append("/**\n * Page Object Model for ").append(className).append(".\n");
            sb.append(" * Auto-generated by Ellithium AI Engine.\n */\n");
            sb.append("public class ").append(className).append(" {\n\n");
            sb.append("    private final DriverActions<?> driverActions;\n\n");

            // Locator fields
            for (String field : locatorFields) {
                sb.append("    ").append(field.trim()).append("\n");
            }
            sb.append("\n");

            // Constructor
            sb.append("    public ").append(className).append("(WebDriver driver) {\n");
            sb.append("        this.driverActions = new DriverActions<>(driver);\n");
            sb.append("    }\n\n");

            // Business action methods
            for (String method : methodBodies) {
                sb.append("    ").append(method.trim()).append("\n\n");
            }
            sb.append("}\n");

            // Validate syntax before writing — reject LLM-generated code with static
            // initializers, extra class blocks, or other malformed constructs.
            String source = sb.toString();
            try {
                StaticJavaParser.parse(source);
            } catch (Exception parseEx) {
                Reporter.log("POM class rejected (syntax error in LLM output): "
                        + parseEx.getMessage(), LogLevel.ERROR);
                return false;
            }

            Path path = Paths.get(outputPath);
            Files.createDirectories(path.getParent());
            Files.writeString(path, source);

            Reporter.log("POM class created: " + outputPath, LogLevel.INFO_GREEN);
            return true;
        } catch (IOException e) {
            Reporter.log("Failed to create POM class: " + e.getMessage(), LogLevel.ERROR);
            return false;
        }
    }

    /**
     * Injects a new locator field and business method into an existing POM class.
     * Uses AST to safely modify the file without breaking compilation.
     *
     * @param filePath        Absolute path to the existing .java POM file
     * @param locatorField    Raw field declaration string (e.g., "private final By searchBox = By.id(\"q\");")
     * @param methodSignature Method signature (e.g., "public LoginPage search(String query)")
     * @param methodBody      Method body (e.g., "driverActions.elements().type(searchBox, query); return this;")
     * @return true if the file was modified successfully
     */
    public static boolean injectIntoExistingPom(String filePath, String locatorField,
                                                  String methodSignature, String methodBody) {
        try {
            File javaFile = new File(filePath);
            if (!javaFile.exists()) {
                Reporter.log("POM file not found for injection: " + filePath, LogLevel.ERROR);
                return false;
            }

            CompilationUnit cu = StaticJavaParser.parse(javaFile);
            Optional<ClassOrInterfaceDeclaration> classOpt = cu.findFirst(ClassOrInterfaceDeclaration.class);

            if (classOpt.isEmpty()) {
                Reporter.log("No class found in file: " + filePath, LogLevel.ERROR);
                return false;
            }

            ClassOrInterfaceDeclaration clazz = classOpt.get();

            // Add locator field (parsed via AST to maintain type safety)
            if (locatorField != null && !locatorField.isEmpty()) {
                BodyDeclaration<?> field = StaticJavaParser.parseBodyDeclaration(locatorField);
                clazz.addMember(field);
            }

            // Add method (parsed via AST)
            if (methodSignature != null && !methodSignature.isEmpty()) {
                String fullMethod = methodSignature + " {\n    " + methodBody + "\n}";
                MethodDeclaration method = StaticJavaParser.parseMethodDeclaration(fullMethod);
                clazz.addMember(method);
            }

            Files.writeString(Paths.get(filePath), cu.toString());
            Reporter.log("Injected into POM class: " + filePath, LogLevel.INFO_GREEN);
            return true;
        } catch (Exception e) {
            Reporter.log("Failed to inject into POM class: " + e.getMessage(), LogLevel.ERROR);
            return false;
        }
    }
}
