package pages;

import Ellithium.Utilities.interactions.DriverActions;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;

/**
 * Page Object Model for LoginPage.
 * Auto-generated by Ellithium AI Engine.
 */
public class LoginPage {

    private final DriverActions<?> driverActions;

    private final By user = By.id("user");

    public LoginPage(WebDriver driver) {
        this.driverActions = new DriverActions<>(driver);
    }

    public LoginPage login(String email, String pass) { return this; }

}
