package pages;

import Ellithium.Utilities.interactions.DriverActions;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;

/**
 * Page Object Model for MainPage.
 * Auto-generated by Ellithium AI Engine.
 */
public class MainPage {

    private final DriverActions<?> driverActions;

    private final By dropdownLink = By.linkText("Dropdown");

    public MainPage(WebDriver driver) {
        this.driverActions = new DriverActions<>(driver);
    }

    public MainPage clickDropdown() { driverActions.elements().clickOnElement(dropdownLink); return this; }

}
