package pages;

import Ellithium.Utilities.interactions.DriverActions;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;

/**
 * Page Object Model for SecurePage.
 * Auto-generated by Ellithium AI Engine.
 */
public class SecurePage {

    private final DriverActions<?> driverActions;

    private final By logoutButton = By.cssSelector("a.button.secondary.radius");
    private final By dropdownLink = By.linkText("Dropdown");

    public SecurePage(WebDriver driver) {
        this.driverActions = new DriverActions<>(driver);
    }

    public SecurePage clickLogout() { driverActions.elements().clickOnElement(logoutButton); return this; }

    public void clickDropdown() { driverActions.elements().clickOnElement(dropdownLink); }

}
