name: CI Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  Ubuntu-Helper-Tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
        with:
          java-version: 21
      - uses: ./.github/actions/cleanup
      - name: Run Helper Tests
        run: mvn test -Dtest="Helpers.**.*" -Dsurefire.parallel=classes -DforkCount=7 -DreuseForks=true -DthreadCount=7 -DdataProviderThreadCount=7
      - uses: ./.github/actions/test-results
        with:
          artifact-name: ubuntu-helper-test-results

  Ubuntu-DataBase-Tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
        with:
          java-version: 21
      - uses: ./.github/actions/cleanup
      - name: Run Database Tests
        run: mvn test -Dtest="DB.**.*"
      - uses: ./.github/actions/test-results
        with:
          artifact-name: ubuntu-database-test-results

  Ubuntu-API-Tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
        with:
          java-version: 21
      - uses: ./.github/actions/cleanup
      - name: Run API Tests
        run: mvn test -Dtest="BookingAPITests,ContactListAPITests" -Dsurefire.parallel=classes -DforkCount=2 -DreuseForks=true -DthreadCount=2 -DdataProviderThreadCount=2
      - uses: ./.github/actions/test-results
        with:
          artifact-name: ubuntu-api-test-results

  MacOS-UI-Basic-Tests:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
        with:
          java-version: 21
      - uses: ./.github/actions/cleanup
      - name: Run UI Basic Tests
        run: mvn test -Dtest="loginTests,AmazonSearchTests,AlertsTests,HorizontalSliderTests" -Dsurefire.parallel=classes -DforkCount=4 -DreuseForks=true -DthreadCount=4 -DdataProviderThreadCount=4
      - uses: ./.github/actions/test-results
        with:
          artifact-name: macos-ui-basic-test-results

  MacOS-UI-Actions-Tests:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
        with:
          java-version: 21
      - uses: ./.github/actions/cleanup
      - name: Run UI Actions Tests
        run: mvn test -Dtest="DropDownTests,DragDropTests,HoverPageTests,DynamicLoadingPageTests" -Dsurefire.parallel=classes -DforkCount=4 -DreuseForks=true -DthreadCount=4 -DdataProviderThreadCount=4
      - uses: ./.github/actions/test-results
        with:
          artifact-name: macos-ui-actions-test-results

  MacOS-UI-BDD-Tests:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
        with:
          java-version: 21
      - uses: ./.github/actions/cleanup
      - name: Run UI BDD Tests
        run: mvn test -Dtest="TestRunner" -Dsurefire.parallel=methods -DforkCount=10 -DreuseForks=true -DthreadCount=10 -DdataProviderThreadCount=10
      - uses: ./.github/actions/test-results
        with:
          artifact-name: macos-ui-bdd-test-results