name: CI Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test-ubuntu:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java-version: [21]
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up JDK ${{ matrix.java-version }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java-version }}
          distribution: 'zulu' 

      - name: Build with Maven
        run: mvn clean install -DskipTests -Dgpg.skip

      - name: Run Tests
        run: mvn test -Dgpg.skip

  test-macos:
    runs-on: macos-latest
    strategy:
      matrix:
        java-version: [21]
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up JDK ${{ matrix.java-version }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java-version }}
          distribution: 'zulu' 

      - name: Build with Maven
        run: mvn clean install -DskipTests -Dgpg.skip

      - name: Run Tests
        run: mvn test -Dgpg.skip

  test-windows:
    runs-on: windows-latest
    strategy:
      matrix:
        java-version: [21]
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up JDK ${{ matrix.java-version }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java-version }}
          distribution: 'zulu' 

      - name: Build with Maven
        run: mvn clean install -DskipTests -Dgpg.skip

      - name: Run Tests
        run: mvn test -Dgpg.skip