name: CI Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test-ubuntu:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java-version: [21]
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up JDK ${{ matrix.java-version }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java-version }}
          distribution: 'zulu' 

      - name: Clean up previous test output
        run: |
          rm -rf Test-Output/Reports/*
          rm -rf Test-Output/Logs/*
          rm -rf Test-Output/ScreenShots/Failed/*
          find Test-Output/UpdateChecker/ -type f ! -name 'checker.json' -delete

      - name: Build with Maven
        run: mvn clean install -DskipTests -Dgpg.skip

      - name: Run Tests
        run: mvn test -Dgpg.skip

  test-macos:
    runs-on: macos-latest
    strategy:
      matrix:
        java-version: [21]
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up JDK ${{ matrix.java-version }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java-version }}
          distribution: 'zulu' 

      - name: Clean up previous test output
        run: |
          rm -rf Test-Output/Reports/*
          rm -rf Test-Output/Logs/*
          rm -rf Test-Output/ScreenShots/Failed/*
          find Test-Output/UpdateChecker/ -type f ! -name 'checker.json' -delete

      - name: Build with Maven
        run: mvn clean install -DskipTests -Dgpg.skip

      - name: Run Tests
        run: mvn test -Dgpg.skip

  test-windows:
    runs-on: windows-latest
    strategy:
      matrix:
        java-version: [21]
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up JDK ${{ matrix.java-version }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java-version }}
          distribution: 'zulu' 
          
      - name: Clean up previous test output
        run: |
          del Test-Output\Reports\* || echo "No files to delete"
          del Test-Output\Logs\* || echo "No files to delete"
          del Test-Output\ScreenShots\Failed\* || echo "No files to delete"
          forfiles /p Test-Output\UpdateChecker /s /m *.* /c "cmd /c if @isdir==FALSE if not @file==checker.json del @path"

      - name: Build with Maven
        run: mvn clean install -DskipTests -Dgpg.skip

      - name: Run Tests
        run: mvn test -Dgpg.skip
