name: CI Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  Ubuntu-Helper-Tests:
    runs-on: ubuntu-latest
    env:
      EMAIL_USERNAME: ${{ secrets.EMAIL_USERNAME }}
      EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
      EMAIL_TO_NOTIFY: ${{ secrets.EMAIL_TO_NOTIFY }}
    steps:
      - uses: actions/checkout@v5
      - uses: ./.github/actions/setup
        with:
          java-version: 21
      - uses: ./.github/actions/cleanup
      - name: Run Helper Tests
        run: mvn test -Dtest="Helpers.**.*" -Dsurefire.parallel=classes
      - uses: ./.github/actions/test-results
        with:
          artifact-name: ubuntu-helper-test-results

  Ubuntu-DataBase-Tests:
    runs-on: ubuntu-latest
    env:
      EMAIL_USERNAME: ${{ secrets.EMAIL_USERNAME }}
      EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
      EMAIL_TO_NOTIFY: ${{ secrets.EMAIL_TO_NOTIFY }}
    steps:
      - uses: actions/checkout@v5
      - uses: ./.github/actions/setup
        with:
          java-version: 21
      - uses: ./.github/actions/cleanup
      - name: Run Database Tests
        run: mvn test -Dtest="DB.**.*"
      - uses: ./.github/actions/test-results
        with:
          artifact-name: ubuntu-database-test-results

  Ubuntu-API-Tests:
    runs-on: ubuntu-latest
    env:
      EMAIL_USERNAME: ${{ secrets.EMAIL_USERNAME }}
      EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
      EMAIL_TO_NOTIFY: ${{ secrets.EMAIL_TO_NOTIFY }}
    steps:
      - uses: actions/checkout@v5
      - uses: ./.github/actions/setup
        with:
          java-version: 21
      - uses: ./.github/actions/cleanup
      - name: Run API Tests
        run: mvn test -Dtest="BookingAPITests,ContactListAPITests" -Dsurefire.parallel=classes -Dmaven.test.failure.ignore=true
      - uses: ./.github/actions/test-results
        with:
          artifact-name: ubuntu-api-test-results

  MacOS-UI-Basic-Tests:
    runs-on: macos-latest
    env:
      EMAIL_USERNAME: ${{ secrets.EMAIL_USERNAME }}
      EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
      EMAIL_TO_NOTIFY: ${{ secrets.EMAIL_TO_NOTIFY }}
    steps:
      - uses: actions/checkout@v5
      - uses: ./.github/actions/setup
        with:
          java-version: 21
      - uses: ./.github/actions/cleanup
      - name: Run UI Basic Tests
        run: mvn test -Dtest="loginTests,AmazonSearchTests,AlertsTests,HorizontalSliderTests" -Dsurefire.parallel=classes
      - uses: ./.github/actions/test-results
        with:
          artifact-name: macos-ui-basic-test-results

  MacOS-UI-Actions-Tests:
    runs-on: macos-latest
    env:
      EMAIL_USERNAME: ${{ secrets.EMAIL_USERNAME }}
      EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
      EMAIL_TO_NOTIFY: ${{ secrets.EMAIL_TO_NOTIFY }}
    steps:
      - uses: actions/checkout@v5
      - uses: ./.github/actions/setup
        with:
          java-version: 21
      - uses: ./.github/actions/cleanup
      - name: Run UI Actions Tests
        run: mvn test -Dtest="DropDownTests,DragDropTests,HoverPageTests,DynamicLoadingPageTests" -Dsurefire.parallel=classes
      - uses: ./.github/actions/test-results
        with:
          artifact-name: macos-ui-actions-test-results

  MacOS-UI-BDD-Tests:
    runs-on: macos-latest
    env:
      EMAIL_USERNAME: ${{ secrets.EMAIL_USERNAME }}
      EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
      EMAIL_TO_NOTIFY: ${{ secrets.EMAIL_TO_NOTIFY }}
    steps:
      - uses: actions/checkout@v5
      - uses: ./.github/actions/setup
        with:
          java-version: 21
      - uses: ./.github/actions/cleanup
      - name: Run UI BDD Tests
        run: mvn test -Dtest="TestRunner" -Dsurefire.parallel=methods
      - uses: ./.github/actions/test-results
        with:
          artifact-name: macos-ui-bdd-test-results